routes/web.php
<?php

//revisar
use Illuminate\Support\Facades\Auth;
//Add los controladores
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CandidateController;
use App\Http\Controllers\Admin\TechnologyController;
use App\Http\Controllers\FileUploadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
  
Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
  
Route::group(['middleware' => ['auth']], function(){
    Route::resource('roles', RoleController::class);
    Route::resource('usuarios', UserController::class);
    Route::resource('candidatos', CandidateController::class);
    Route::resource('tecnologias', TechnologyController::class);
   
});

resources/views/candidatos/crear.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Llenar solicitud</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {{-- Mi codigo comienza aqui --}}

            {{-- Validation ponerla por campos--}}

            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Ops!</strong> Revise los datos introducidos.<br/>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
    {{-- Revisar creo que si pongo el files true, no tengo que agregar el enctype --}}
            {!! Form::open(['route' => 'candidatos.store', 'method' => 'POST', 'files' => true]) !!}
            <div class="row">
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        @error('name')
                        <small class="text-danger">{{ $message }}</small>
                    @enderror
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="apellidos">Apellidos</label>
                        {!! Form::text('apellidos', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="email">Email</label>
                        {!! Form::text('email', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="grado_id">Nivel de escolaridad</label>
                        {{-- {!! Form::select('grado_id[]', null, ['class' => 'form-control']) !!}  --}}
                        {{-- {!! Form::select('grados[]', $grados->pluck('name'),[], array('class'=>'form-control', 'placeholder'=>'Seleccione su nivel de escolaridad')) !!} --}}
                         {!! Form::select('grado_id', $grados, [], array('class'=>'form-control', 'placeholder'=>'Seleccione su nivel de escolaridad')) !!} 
                    </div> 
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="password">Password</label>
                        {!! Form::password('password', ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="confirm-password">Confirmar contraseña</label>
                        {!! Form::password('confirm-password', ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="telefono1">Movil</label>
                        {!! Form::text('telefono1', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="telefono2">Teléfono Casa</label>
                        {!! Form::text('telefono2', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div>
            {{-- <div class="row">
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="escolaridad">Grado</label>
                        {!! Form::select('escolaridad[]', $candidato, [], ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="fechagraduacion">Año de graduado</label>
                        {!! Form::text('fechagraduacion', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
            </div> --}}
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="resumen">Resumen</label>
                        {!! Form::textarea('resumen', null, ['class' => 'form-control input', 'cols' => 20, 'rows' => 4, 'required' => '', 'maxlength' => '250']) !!}
                    </div>
                </div>
{{-- CURRICULUM VITAE --}}
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="cv">Subir CV</label>
                        {!! Form::file('cv', ['class' => 'form-control']) !!}
                    </div>
                </div> 
                <div class="col-xs-12 col-sm-12 col-md-12">
                    </br>
                    <div class="form-group">
                        <label for="">Skills & Techs</label>
                        </br>
                        {{-- Shows only skills and techs, wanna add chose the experience too --}}
                        @foreach ($tecnologias as $value)
                            <label>{!! Form::checkbox('tecnologias[]', $value->id, false, ['class' => 'mr-1']) !!}
                                {{ $value->name }}</label>
                            {{-- @if (isset($_POST['tecnologias'])) --}}
                          {{--    <label> {!!Form::select('experiencia', ['1','2','3','4'],  null, ['placeholder' => 'Años de experiencia...'])!!}
                            </label> --}}
                           {{-- // @endif --}}
                            </br>
                        @endforeach
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>

    </div>
@stop

resources/views/candidatos/editar.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar solicitud</h1>
@stop

@section('content')
    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            {{-- Mi codigo comienza aqui --}}
            {{-- Validation --}}
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Ops!</strong> Revise los datos introducidos.<br />
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            {!! Form::model($candidato, ['route' => ['candidatos.update', $candidato->id], 'method' => 'PUT', 'files' => true]) !!}
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="apellidos">Apellidos</label>
                        {!! Form::text('apellidos', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="email">Email</label>
                        {!! Form::text('email', null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-group">
                        <label for="grado_id">Nivel de escolaridad</label>
                        {!! Form::select('grado_id', $grados->toArray(), old('grado_id', $candidato->grado_id), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Seleccione su nivel de escolaridad']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="password">Password</label>
                        {!! Form::password('password', ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="confirm-password">Confirmar contraseña</label>
                        {!! Form::password('confirm-password', ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="text">Resumen</label>
                        {!! Form::textarea('resumen', null, ['class' => 'form-control input', 'cols' => 20, 'rows' => 4, 'required' => '', 'maxlength' => '250']) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="cv">Subir CV</label>
                        {!! Form::file('cv', ['class' => 'form-control']) !!}
                    </div>
                </div>
                </br>
                <div class="form-group">
                    <label for="tecnologias">Tecnologias y Habilidades</label>
                    </br>
                    {{-- Esto lo arreglo con js --}}
                    @foreach ($tecnologias as $value)
                        <label>{!! Form::checkbox('tecnologias[]', $value->id, in_array($value->id, $candidatoskills) ? true : false, ['class' => 'name']) !!}
                            {{ $value->name }}</label>
                        <br />
                    @endforeach
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                {{-- <button type="submit" class="btn btn-primary">Guardar</button> --}}
                {!! Form::submit('Actualizar Solicitud', ['class' => 'btn btn-primary']) !!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
    </div>
@stop

resources/views/candidatos/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Candidatos</h1>
@stop

@section('content')
    {{-- Mi codigo comienza aqui --}}
    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            <input class="form-control" placeholder="Ingrese el nombre o correo del un usuario">
        </div>
        <div class="card-body">
            <a class="btn btn-primary" href="{{ route('candidatos.create') }}">Llenar solicitud</a>
            {{-- Esta opcion no va a aqui, solo probando --}}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="display:none">Id</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th>Skills</th>
                        <th>Curriculum</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($candidates as $candidate)
                        <tr>
                            <td style="display:none">{{ $candidate->id }}</td>
                            <td>{{ $candidate->name }}</td>
                            <td>{{ $candidate->email }}</td>
                            <td>
                                {{-- {{ $candidate->technologies->pluck('name')}} --}}
                                @foreach ($candidate->technologies as $tecnologia)
                                    {{ $tecnologia->name }}
                                @endforeach
                            </td>
                            <td>
                                {{$candidate->cv}}
                              {{-- <a href="{{ storage_path("app/cv/" . "$candidate->cv") }}">{{$candidate->cv }}</a></td>   --}}
                              {{-- <a href="{{ Storage::download("storage_path("app/cv/" . "$candidate->cv")") }}">{{$candidate->cv }}</a></td> --}}
                              {{-- @foreach ($paths as $path)
                              <a href="{{ Storage::download("path") }}">{{$candidate->cv }}</a>
                              @endforeach --}}
                            </td>
                            <td>
                                <a class="btn btn-info" style="display: inline" href="{{ route('candidatos.edit', $candidate->id) }}">Editar</a>

                                @can('Eliminar candidato')
                                {!! Form::open(['method' => 'DELETE', 'route' => ['candidatos.destroy', $candidate->id], 'style' => 'display:inline']) !!}
                                {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
                                @endcan
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="pagination justify-content-end">
            {!! $candidates->links() !!}
        </div>
    </div>

@stop