routes/web.php
<?php

//revisar
use Illuminate\Support\Facades\Auth;
//Add los controladores
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CandidateController;
use App\Http\Controllers\Admin\TechnologyController;
use App\Http\Controllers\FileUploadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
  
Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
  
Route::group(['middleware' => ['auth']], function(){
    Route::resource('roles', RoleController::class);
    Route::resource('usuarios', UserController::class);
    Route::resource('candidatos', CandidateController::class);
    Route::resource('tecnologias', TechnologyController::class);
   
});

resources/views/tecnologias/crear.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Adicionar Tecnología</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {{-- Mi codigo comienza aqui --}}

            {{-- Validation --}}
            {!! Form::open(['route' => 'tecnologias.store', 'method' => 'POST']) !!}

            <div class="form-group">
                {!! Form::label('name', 'Nombre') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre de la tecnología']) !!}
                @error('name')
                    <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}

        </div>
    </div>
@stop

resources/views/tecnologias/editar.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar Tecnologías & Habilidades</h1>
@stop

@section('content')
{!! Form::model($tecnologia, ['method' => 'PUT', 'route' => ['tecnologias.update', $tecnologia->id]]) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <label for="name">Tecnología</label>
            {!! Form::text('name', null, array('class'=>'form-control')) !!}
        </div>
    </div>
 
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
</div>
{!! Form::close() !!}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/tecnologias/experience.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Adicionar Tecnología</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        {{-- Mi codigo comienza aqui --}}

        {{-- Validation --}}

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Ops!</strong> Revise los datos por favor.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => 'tecnologias.store', 'method' => 'POST']) !!}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="name">Nombre</label>
                    {!! Form::text('name', null, ['class' => 'form-control']) !!}
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="resumen">Resumen</label>
                    {!! Form::textarea('resumen', null, ['class' => 'form-control input', 'cols' => 20, 'rows' => 4, 'required' => '', 'maxlength' => '250']) !!}
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                </br>
                <div class="form-group">
                    <label for="">Skills & Techs</label>
                    </br>
                    {{-- Shows only skills and techs, wanna add chose the experience too --}}
                    @foreach ($tecnologias as $value)
                        <label>{{ Form::checkbox('tecnologias[]', $value->id, null, ['class' => 'mr-1']) }}
                            {{ $value->name }}</label>
                        </br>
                    @endforeach 
                </div>
            </div> 
            <div class="col-xs-12 col-sm-12 col-md-12">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
        {!! Form::close() !!}

    </div>

</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/tecnologias/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Tecnologías & Habilidades</h1>
@stop

@section('content')
    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            <input class="form-control" placeholder="Ingrese el nombre de la tecnología o habilidad">
        </div>
        <div class="card-body">

            <a class="btn btn-primary" href="{{ route('tecnologias.create') }}">Nueva tecnología</a>
            {{-- Esta opcion no va a aqui, solo probando --}}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="display:none">Id</th>
                        <th> </th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tecnologias as $tecnologia)
                        <tr>
                            <td style="display:none">{{ $tecnologia->id }}</td>
                            <td><a href=" {{ route('tecnologias.show', $tecnologia->id) }}">{{ $tecnologia->name }} </a></td>
                            {{-- puedo pasar solo el id --}}

                            <td>
                                <a class="btn btn-info" href="{{ route('tecnologias.edit', $tecnologia->id) }}">Editar</a>
                                {!! Form::open(['method' => 'DELETE', 'route' => ['tecnologias.destroy', $tecnologia->id], 'style' => 'display:inline']) !!}
                                {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

resources/views/tecnologias/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Usuarios con experiencia en: {{ $tecnologia->name }}</h1>
@stop

@section('content')

    <div class="card">
        <div class="card-header">
            <input class="form-control" placeholder="Ingrese el nombre de la tecnología o habilidad">
        </div>
        <div class="card-body">

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="display:none">Id</th>
                        <th>Nombre y apellidos</th>
                        <th>Experiencia</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tecnologia->candidates as $candidato)
                        <tr>
                            <td style="display:none">Id</td>
                            <td>{{ $candidato->name }} {{$candidato->apellidos}}</td>
                        </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop